using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace kortspill
{
  public class Card
  {
    //Each card is generated by combining Type and number which comes from CardType enum and CardNumber enum
    
    public CardType CardType { get; set; }
    public CardNumber CardNumber { get; set; }
  }
}
